const ENTITY = 'VIDEO'
export const SET_LOADING = `${ENTITY}_SET_LOADING`
export const SET_ERROR = `${ENTITY}_SET_ERROR`
export const FETCH_ALL_VIDEOS = 'FETCH_ALL_VIDEOS'
export const UPDATE_ALL_VIDEOS = 'UPDATE_ALL_VIDEOS'
export const SHARE_VIDEO = `${ENTITY}_SHARE_VIDEO`
export const VIDEO_SHARED = `${ENTITY}_SHARED`